action_selection:
  n_possible_actions: 90
  n_actions: 7
  shape: [112, 90] # h, w
  selection_strategy: "greedy_entropy" # "downstream_gradient_descent" | "downstream_propagation" | "greedy_entropy" | "uniform_random" | "covariance"
  pfield:
    downsample: 1
    downmix: 1
    norm: False

downstream_task: null

diffusion_inference:
  run_dir: "{output_dir}/ddim/2025_02_26_160545_ddim_train_echonet_112_3_frames/hub"
  num_steps: 500
  initial_step: 450 # [0, num_steps]
  batch_size: 2 # posterior samples
  # guidance_method: "anisotropic_dps"
  operator: "inpainting"
  guidance_method: "anisotropic_dps"
  guidance_kwargs:
    omega: 3
    initial_omega: 1
  reconstruction_method: "choose_first" # "choose_first" | "mean"
  hard_project: false

io_config:
  plot_step_overview: false
  plot_frame_overview: false
  plot_frames_for_presentation: true
  plot_frames_for_presentation_kwargs:
    scan_convert_order: 0
    scan_convert_resolution: 0.1 # for speed 1.0, for quality 0.1
  save_target_img: false
  save_animation: true
  scan_convert: true
  scan_conversion_angles: [-45, 45]
  frame_cutoff: 30
  gif_fps: 30
  verbose: false
  reconstruction_sharpness_std: 0.025
