action_selection:
  n_possible_actions: 90
  n_actions: 14
  shape: [256, 90] # h, w
  selection_strategy: "greedy_entropy" # "downstream_gradient_descent" | "downstream_propagation" | "greedy_entropy" | "uniform_random" | "covariance"
  # pfield:
  #   downsample: 1
  #   downmix: 1
  #   percentile: 80
  #   alpha: 2.0
  #   norm: True
  # kwargs:
  #   assert_equal_spacing: false
  #   std_dev: 2
  #   num_lines_to_update: 5

downstream_task: null

diffusion_inference:
  # run_dir: "/mnt/z/Ultrasound-BMD/Ultrasound-BMd/pretrained/ddim/2025_05_16_135444_ddim_train_echonetlvh_256/zeahub"
  run_dir: "/mnt/z/Ultrasound-BMD/Ultrasound-BMd/pretrained/ddim/2025_05_17_120937_ddim_train_echonetlvh_256_96_3_frames/zeahub"
  num_steps: 500
  initial_step: 450 # [0, num_steps]
  batch_size: 4 # posterior samples
  operator: inpainting
  guidance_method: dps
  guidance_kwargs:
    omega: 9
    initial_omega: 3
  reconstruction_method: "choose_first" # "choose_first" | "mean"
  hard_project: true

io_config:
  plot_step_overview: false
  plot_frame_overview: false
  plot_frames_for_presentation: true
  plot_frames_for_presentation_kwargs:
    scan_convert_order: 1
    scan_convert_resolution: 0.5 # for speed 1.0, for quality 0.1
  save_target_img: false
  save_animation: true
  scan_convert: true
  scan_conversion_angles: [-45, 45]
  frame_cutoff: 30
  gif_fps: 30
  verbose: false
  reconstruction_sharpness_std: 0.04

data:
  target_sequence: "{data_root}/USBMD_datasets/2024_USBMD_cardiac_S51/HDF5/20240701_P3_PLAX_0000.hdf5"
  data_type: data/raw_data
  image_range: [-60, -10]