action_selection:
  n_possible_actions: 90
  n_actions: 45
  shape: [112, 90] # h, w
  selection_strategy: "greedy_entropy" # "downstream_gradient_descent" | "downstream_propagation" | "greedy_entropy" | "uniform_random" | "covariance"

downstream_task: null

diffusion_inference:
  run_dir: hf://zeahub/ulsa
  num_steps: 500
  initial_step: 450 # [0, num_steps]
  batch_size: 4 # posterior samples
  operator: inpainting
  guidance_method: dps
  guidance_kwargs:
    omega: 3
    initial_omega: 1
  reconstruction_method: "choose_first" # "choose_first" | "mean"
  hard_project: true

io_config:
  plot_step_overview: false
  plot_frame_overview: false
  plot_frames_for_presentation: true
  plot_frames_for_presentation_kwargs:
    scan_convert_order: 0
    scan_convert_resolution: 0.1 # for speed 1.0, for quality 0.1
  save_target_img: false
  save_animation: true
  scan_convert: true
  scan_conversion_angles: [-45, 45]
  frame_cutoff: 39
  gif_fps: 30
  verbose: false
  reconstruction_sharpness_std: 0.04

data:
  target_sequence: "{data_root}/USBMD_datasets/2024_USBMD_cardiac_S51/HDF5/20240701_P1_A4CH_0001.hdf5"
  data_type: data/raw_data
  # image_range: [-65, -20]
  image_range: null

