action_selection:
  n_possible_actions: 256
  n_actions: 2
  shape: [256, 256]
  selection_strategy: "downstream_task_selection" # "downstream_gradient_descent" | "downstream_propagation" | "greedy_entropy" | "uniform_random" | "covariance"
  kwargs:
    # downstream_task_key: "echonetlvh_segmentation"
    downstream_task_key: "echonetlvh_measurement"
    measurement_type: "IVS"

downstream_task: "echonetlvh_segmentation"

diffusion_inference:
  run_dir: "{output_dir}/ddim/2025_05_16_135444_ddim_train_echonetlvh_256/zeahub"
  num_steps: 500
  initial_step: 50 # [0, num_steps]
  batch_size: 4 # posterior samples
  guidance_kwargs:
    initial_omega: 1
    omega: 1
  reconstruction_method: "choose_first" # "choose_first" | "maximum_likelihood" | "mean"
  hard_project: true

io_config:
  plot_step_overview: false
  plot_frame_overview: false
  plot_frames_for_presentation: true
  plot_frames_for_presentation_kwargs:
    scan_convert_order: 0
    scan_convert_resolution: 0.5 # for speed 1.0, for quality 0.1
  save_target_img: false
  save_animation: true
  scan_convert: true
  scan_conversion_angles: [-45, 45]
  frame_cutoff: 5
  gif_fps: 30
  verbose: false
  reconstruction_sharpness_std: 0.025

data:
  target_sequence: "{data_root}/USBMD_datasets/echonetlvh/val/0X86F054EEAE4663C0.hdf5"
  data_type: data/image
  image_range: [-60, 0]